stages:
  - test
  - build

test:
  stage: test
  script:
    - echo "some tests should be done..."

# Building with Docker in Docker
build:
  stage: build
  image: docker:stable
  services:
    - docker:19-dind
  script:
    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then TAG="latest"; else TAG=$CI_COMMIT_REF_NAME; fi
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker image build -f Dockerfile -t $CI_REGISTRY_IMAGE:$TAG .
    - docker image push $CI_REGISTRY_IMAGE:$TAG
