FROM rust:1-buster as build

WORKDIR /usr/src/worker-rust
COPY rust .

RUN cargo install --path .

FROM debian:buster-slim
COPY --from=build /usr/src/worker-rust/target/release/worker-rust /usr/local/bin/worker-rust
CMD ["worker-rust"]
